  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Benson
 */
public class home extends javax.swing.JFrame {
public int i =0;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTwoArrow = new javax.swing.JButton();
        btnAddNewPatient = new javax.swing.JButton();
        btnAddDiagnosisInformation = new javax.swing.JButton();
        btnPatientHistory = new javax.swing.JButton();
        btnUpdatePatientRecord = new javax.swing.JButton();
        btnHospitalInformation = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTwoArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/two arrow.png"))); // NOI18N
        btnTwoArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoArrowActionPerformed(evt);
            }
        });
        getContentPane().add(btnTwoArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 54, -1));

        btnAddNewPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/add new patient.png"))); // NOI18N
        btnAddNewPatient.setText("Add New Patient");
        btnAddNewPatient.setPreferredSize(new java.awt.Dimension(249, 59));
        btnAddNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewPatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddNewPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, -1, -1));

        btnAddDiagnosisInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/add diag.png"))); // NOI18N
        btnAddDiagnosisInformation.setText("Add Diagnosis Information");
        btnAddDiagnosisInformation.setPreferredSize(new java.awt.Dimension(249, 59));
        btnAddDiagnosisInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiagnosisInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddDiagnosisInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, -1, -1));

        btnPatientHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/rsz_history1.png"))); // NOI18N
        btnPatientHistory.setText("Full Patient History");
        btnPatientHistory.setPreferredSize(new java.awt.Dimension(249, 59));
        btnPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatientHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 275, -1, -1));

        btnUpdatePatientRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/rsz_update_details.png"))); // NOI18N
        btnUpdatePatientRecord.setText("Update Patient Record");
        btnUpdatePatientRecord.setPreferredSize(new java.awt.Dimension(249, 59));
        btnUpdatePatientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdatePatientRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 352, -1, -1));

        btnHospitalInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/rsz_hospital_information.png"))); // NOI18N
        btnHospitalInformation.setText("Hospital Information");
        btnHospitalInformation.setPreferredSize(new java.awt.Dimension(249, 59));
        btnHospitalInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnHospitalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 429, -1, -1));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/exit.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setPreferredSize(new java.awt.Dimension(249, 59));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 506, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/management/system/home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout?","Warning!!",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
        setVisible(false);
        new login().setVisible(true);
        }            
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTwoArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoArrowActionPerformed
        // TODO add your handling code here:
        if(i==0){
        btnAddNewPatient.setLocation(90, 30);
        btnAddDiagnosisInformation.setLocation(333, 30);
        btnPatientHistory.setLocation(576, 30);
        btnUpdatePatientRecord.setLocation(819, 30);
        btnHospitalInformation.setLocation(1062, 30);
        btnLogout.setLocation(1062, 89);
        i=1;
        }
        else{
        btnAddNewPatient.setLocation(10, 107);
        btnAddDiagnosisInformation.setLocation(10, 184);
        btnPatientHistory.setLocation(10, 261);
        btnUpdatePatientRecord.setLocation(10, 338);
        btnHospitalInformation.setLocation(10, 415);
        btnLogout.setLocation(10, 490);
        i=0;
        }
    }//GEN-LAST:event_btnTwoArrowActionPerformed

    private void btnAddNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewPatientActionPerformed
        // TODO add your handling code here:
        
        new addNewPatientRecord().setVisible(true);
    }//GEN-LAST:event_btnAddNewPatientActionPerformed

    private void btnAddDiagnosisInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiagnosisInformationActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new addDiagnosisInformation().setVisible(true);
    }//GEN-LAST:event_btnAddDiagnosisInformationActionPerformed

    private void btnPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientHistoryActionPerformed
        // TODO add your handling code here:
        new fullHistoryOfThePatient().setVisible(true);
    }//GEN-LAST:event_btnPatientHistoryActionPerformed

    private void btnUpdatePatientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientRecordActionPerformed
        // TODO add your handling code here:
        new updatePatientRecord().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnUpdatePatientRecordActionPerformed

    private void btnHospitalInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalInformationActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new hospitalInformation().setVisible(true);
    }//GEN-LAST:event_btnHospitalInformationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDiagnosisInformation;
    private javax.swing.JButton btnAddNewPatient;
    private javax.swing.JButton btnHospitalInformation;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPatientHistory;
    private javax.swing.JButton btnTwoArrow;
    private javax.swing.JButton btnUpdatePatientRecord;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
